In [1]:
#import libraries
from google.colab import files
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

#Read the dataset from drive
df=pd.read_csv("/content/Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [2]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [3]:
#check for duplication
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [4]:
print(df['CreditScore'].describe())

count    10000.000000
mean       650.528800
std         96.653299
min        350.000000
25%        584.000000
50%        652.000000
75%        718.000000
max        850.000000
Name: CreditScore, dtype: float64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.drop(['Surname','Geography','Gender'],axis=1,inplace=True)
df

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [7]:
Scaler=MinMaxScaler()
df1=pd.DataFrame(Scaler.fit_transform(df))
df1

,0,1,2,3,4,5,6,7,8,9,10
0,0.0000,0.275616,0.538,0.324324,0.2,0.000000,0.000000,1.0,1.0,0.506735,1.0
1,0.0001,0.326454,0.516,0.310811,0.1,0.334031,0.000000,0.0,1.0,0.562709,0.0
2,0.0002,0.214421,0.304,0.324324,0.8,0.636357,0.666667,1.0,0.0,0.569654,1.0
3,0.0003,0.542636,0.698,0.283784,0.1,0.000000,0.333333,0.0,0.0,0.469120,0.0
4,0.0004,0.688778,1.000,0.337838,0.2,0.500246,0.000000,1.0,1.0,0.395400,0.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,0.9996,0.162119,0.842,0.283784,0.5,0.000000,0.333333,1.0,0.0,0.481341,0.0
9996,0.9997,0.016765,0.332,0.229730,1.0,0.228657,0.000000,1.0,1.0,0.508490,0.0
9997,0.9998,0.075327,0.718,0.243243,0.7,0.000000,0.000000,0.0,1.0,0.210390,1.0
9998,0.9999,0.466637,0.844,0.324324,0.3,0.299226,0.333333,1.0,0.0,0.464429,1.0
9999,1.0000,0.250483,0.884,0.135135,0.4,0.518708,0.000000,1.0,0.0,0.190914,0.0

In [8]:
X = df1.iloc[:, :-1].values
print(X)

[[0.00000000e+00 2.75616127e-01 5.38000000e-01 ... 1.00000000e+00
  1.00000000e+00 5.06734893e-01]
 [1.00010001e-04 3.26454364e-01 5.16000000e-01 ... 0.00000000e+00
  1.00000000e+00 5.62708739e-01]
 [2.00020002e-04 2.14421435e-01 3.04000000e-01 ... 1.00000000e+00
  0.00000000e+00 5.69654352e-01]
 ...
 [9.99799980e-01 7.53273144e-02 7.18000000e-01 ... 0.00000000e+00
  1.00000000e+00 2.10390092e-01]
 [9.99899990e-01 4.66636532e-01 8.44000000e-01 ... 1.00000000e+00
  0.00000000e+00 4.64429053e-01]
 [1.00000000e+00 2.50483021e-01 8.84000000e-01 ... 1.00000000e+00
  0.00000000e+00 1.90914232e-01]]

In [9]:
y = df1.iloc[:,-1].values
print(y)

[1. 0. 1. ... 1. 1. 0.]

In [10]:

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=25)

In [11]:
print(X_train)

[[0.8239824  0.75304913 0.578      ... 0.         0.         0.78326095]
 [0.71057106 0.1273456  0.452      ... 0.         0.         0.67623103]
 [0.51765177 0.6296437  0.812      ... 1.         1.         0.82199385]
 ...
 [0.29342934 0.49796991 0.562      ... 1.         1.         0.29018491]
 [0.66186619 0.76243355 0.572      ... 0.         1.         0.65962699]
 [0.85108511 0.81464384 0.4        ... 0.         0.         0.83236264]]

In [12]:
print(len(X_train))

8000

In [13]:
print(X_test)

[[0.35553555 0.25358316 0.356      ... 1.         1.         0.74957508]
 [0.40784078 0.49897796 0.612      ... 1.         1.         0.98984628]
 [0.84458446 0.45054782 0.666      ... 1.         0.         0.43308231]
 ...
 [0.82258226 0.95380597 0.64       ... 1.         0.         0.49529815]
 [0.10541054 0.70929121 0.504      ... 1.         0.         0.1518546 ]
 [0.04120412 0.48242523 0.79       ... 1.         1.         0.70226677]]

In [14]:
print(len(X_test))

2000